services:
  postgres:
    image: postgres:13
    container_name: loyalty-app-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: loyalty-app-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d loyalty-app-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: